name: Generate cypress script

on:
  schedule:
  - cron: '10 * * * *'

jobs:
  cypress-test:
    name: Run on Chrome 83
    runs-on: macos-latest
    container: cypress/browsers:node12.18.0-chrome83-ff77
    steps:
      - uses: actions/checkout@v2
      
      - name:Install cypress and verify
      run: |
        npm ci
        $(npm bin)/cypress verify

    strategy:
      matrix:
        node-version: [14.x, 16.x, 18.x]
    
    steps:
    - uses: actions/checkout@v3

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        start: npm run runtests


