name: NodeJS with Webpack

on:
  schedule:
  - cron: '*/6 * * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Cypress run
      uses: cypress-io/github-action@v2

    - name: Build
      run: |
        npm install
        npm start
